# Dockerfile

FROM python:3.11-slim 
WORKDIR /app 

# 1. Install Dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 2. Copy the entire repository content (including the dagster/ folder)
COPY . /app

# 3. Execution: Point to the files inside the 'dagster/' subfolder
# The Code Server will run the definitions file found at /app/dagster/definitions.py

CMD ["dagster", "dev", "-f", "/app/dagster/definitions.py", "-d", "/app/dagster", "--host", "0.0.0.0"]